services:
  gupea-espikning:
    image: docker.ub.gu.se/elixir-dev:1.18.4-otp-27
    environment:
      - MIX_ENV=dev
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - "../:/app"
networks:
  default:
    name: dspace_dspace-net
    external: true
